import ucpopy.globals as g
from ucpopy.structs import *
from ucpopy.ucpop import plan

g.templates = [
    P_STEP(
        id=[],
        action=["CHANGE-COMPRESSOR", "?X", "?Y", "?A"],
        parms=["?X", "?Y", "?A"],
        precond=[
            ":AND",
            [":NEQ", "?X", "?Y"],
            ["BACKPLANE", "?A"],
            [":NOT", ["IN-PLACE", "?A"]],
            ["COVERS", "?A", "?X"],
            ["COMPRESSOR", "?X"],
            ["COMPRESSOR", "?Y"],
            ["ATTACHED", "?X"],
            [":NOT", ["ATTACHED", "?Y"]],
        ],
        add=[
            EFFECT(
                id=[], forall=[], precond=[], ranking=[], add=[["COVERS", "?A", "?Y"]]
            ),
            EFFECT(
                id=[],
                forall=[],
                precond=[],
                ranking=[],
                add=[[":NOT", ["COVERS", "?A", "?X"]]],
            ),
            EFFECT(id=[], forall=[], precond=[], ranking=[], add=[["ATTACHED", "?Y"]]),
            EFFECT(
                id=[],
                forall=[],
                precond=[],
                ranking=[],
                add=[[":NOT", ["ATTACHED", "?X"]]],
            ),
        ],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["STOP-FRIDGE", "?F"],
        parms=["?F"],
        precond=["FRIDGE-ON", "?F"],
        add=[
            EFFECT(
                id=[],
                forall=[],
                precond=[],
                ranking=[],
                add=[[":NOT", ["FRIDGE-ON", "?F"]]],
            )
        ],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["START-FRIDGE", "?F", "?A", "?B", "?C", "?D", "?X"],
        parms=["?F", "?A", "?B", "?C", "?D", "?X"],
        precond=[
            ":AND",
            [":NEQ", "?A", "?B"],
            [":NEQ", "?A", "?C"],
            [":NEQ", "?A", "?D"],
            [":NEQ", "?B", "?C"],
            [":NEQ", "?B", "?D"],
            [":NEQ", "?C", "?D"],
            ["BACKPLANE", "?X"],
            ["IN-PLACE", "?X"],
            ["PART-OF", "?X", "?F"],
            ["HOLDS", "?A", "?X"],
            ["HOLDS", "?B", "?X"],
            ["HOLDS", "?C", "?X"],
            ["HOLDS", "?D", "?X"],
            ["SCREWED", "?A"],
            ["SCREWED", "?B"],
            ["SCREWED", "?C"],
            ["SCREWED", "?D"],
            [":NOT", ["FRIDGE-ON", "?F"]],
        ],
        add=[
            EFFECT(id=[], forall=[], precond=[], ranking=[], add=[["FRIDGE-ON", "?F"]])
        ],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["ATTACH-BACKPLANE", "?X", "?F", "?A", "?B", "?C", "?D"],
        parms=["?X", "?F", "?A", "?B", "?C", "?D"],
        precond=[
            ":AND",
            ["BACKPLANE", "?X"],
            [":NEQ", "?A", "?B"],
            [":NEQ", "?A", "?C"],
            [":NEQ", "?A", "?D"],
            [":NEQ", "?B", "?C"],
            [":NEQ", "?B", "?D"],
            [":NEQ", "?C", "?D"],
            [":NOT", ["IN-PLACE", "?X"]],
            ["PART-OF", "?X", "?F"],
            [":NOT", ["FRIDGE-ON", "?F"]],
            ["HOLDS", "?A", "?X"],
            ["HOLDS", "?B", "?X"],
            ["HOLDS", "?C", "?X"],
            ["HOLDS", "?D", "?X"],
            [":NOT", ["SCREWED", "?A"]],
            [":NOT", ["SCREWED", "?B"]],
            [":NOT", ["SCREWED", "?C"]],
            [":NOT", ["SCREWED", "?D"]],
        ],
        add=[
            EFFECT(id=[], forall=[], precond=[], ranking=[], add=[["IN-PLACE", "?X"]])
        ],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["REMOVE-BACKPLANE", "?X", "?F", "?A", "?B", "?C", "?D"],
        parms=["?X", "?F", "?A", "?B", "?C", "?D"],
        precond=[
            ":AND",
            ["BACKPLANE", "?X"],
            [":NEQ", "?A", "?B"],
            [":NEQ", "?A", "?C"],
            [":NEQ", "?A", "?D"],
            [":NEQ", "?B", "?C"],
            [":NEQ", "?B", "?D"],
            [":NEQ", "?C", "?D"],
            ["IN-PLACE", "?X"],
            ["PART-OF", "?X", "?F"],
            [":NOT", ["FRIDGE-ON", "?F"]],
            ["HOLDS", "?A", "?X"],
            ["HOLDS", "?B", "?X"],
            ["HOLDS", "?C", "?X"],
            ["HOLDS", "?D", "?X"],
            [":NOT", ["SCREWED", "?A"]],
            [":NOT", ["SCREWED", "?B"]],
            [":NOT", ["SCREWED", "?C"]],
            [":NOT", ["SCREWED", "?D"]],
        ],
        add=[
            EFFECT(
                id=[],
                forall=[],
                precond=[],
                ranking=[],
                add=[[":NOT", ["IN-PLACE", "?X"]]],
            )
        ],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["SCREW", "?X", "?Y"],
        parms=["?X", "?Y"],
        precond=[
            ":AND",
            ["SCREW", "?X"],
            ["BACKPLANE", "?Y"],
            [":NOT", ["SCREWED", "?X"]],
            ["HOLDS", "?X", "?Y"],
        ],
        add=[EFFECT(id=[], forall=[], precond=[], ranking=[], add=[["SCREWED", "?X"]])],
        cache=[],
    ),
    P_STEP(
        id=[],
        action=["UNSCREW", "?X", "?Y"],
        parms=["?X", "?Y"],
        precond=[
            ":AND",
            ["SCREW", "?X"],
            ["BACKPLANE", "?Y"],
            ["SCREWED", "?X"],
            ["HOLDS", "?X", "?Y"],
        ],
        add=[
            EFFECT(
                id=[],
                forall=[],
                precond=[],
                ranking=[],
                add=[[":NOT", ["SCREWED", "?X"]]],
            )
        ],
        cache=[],
    ),
]
g.axioms = []
g.dynamic_pred = [
    "FRIDGE-ON",
    "SCREWED",
    "FRIDGE",
    "ATTACHED",
    "COVERS",
    "OK",
    "BACKPLANE",
    "SCREW",
    "COMPRESSOR",
    "IN-PLACE",
    "HOLDS",
    "PART-OF",
]
initial = [
    ["SCREW", "S1"],
    ["SCREW", "S2"],
    ["SCREW", "S3"],
    ["SCREW", "S4"],
    ["BACKPLANE", "B1"],
    ["COMPRESSOR", "C1"],
    ["COMPRESSOR", "C2"],
    ["FRIDGE", "F1"],
    ["COVERS", "B1", "C1"],
    ["PART-OF", "B1", "F1"],
    ["HOLDS", "S1", "B1"],
    ["HOLDS", "S2", "B1"],
    ["HOLDS", "S3", "B1"],
    ["HOLDS", "S4", "B1"],
    ["OK", "C1"],
    ["OK", "C2"],
    ["FRIDGE-ON", "F1"],
    ["SCREWED", "S1"],
    ["SCREWED", "S2"],
    ["SCREWED", "S3"],
    ["SCREWED", "S4"],
    ["IN-PLACE", "B1"],
    ["ATTACHED", "C1"],
]
goals = [":AND", ["ATTACHED", "C2"], ["OK", "C2"], ["FRIDGE-ON", "F1"]]
a = plan(initial, goals)
a[0].display()
